### ISSUE TITLE
Using govcr as audit tool

### ISSUE THREAD

**Issue by llonchj** [seborama/govcr#28]
Hi @seborama! 

Thank you for govcr, is a fantastic library.

I am planning to use this library for 2 purposes:

1. Mock test responses 
2. Store the cassettes as a audit tool for a project

The second use is not the intended library use. Do you know a better library to store network requests in golang? If not, what will be the best strategy to turn govcr agnostic to persistance (i.e. .cassette files, databases, etc..)?

Thanks,

**Comment by seborama** [comment]
Hi @llonchj ,

I'm pleased to hear that you're enjoying `govcr`.

Searching the internet reveals a few options but I'm not sure what advice to give you. I guess it depends on your precise use-case.

Kind regards,
Seb

**Comment by llonchj** [comment]
Thanks @seborama!
