### ISSUE TITLE
json: unsupported type: func(...

### ISSUE THREAD

**Issue by leighmcculloch** [seborama/govcr#31]
I'm using govcr but when I have logging turned on I see the following message:

```
2018/07/25 06:21:15 json: unsupported type: func(string, []uint8, int) ([]uint8, bool)
```

Also, after running the test I don't see any new files at the `CassettePath` I have configured.

**Comment by seborama** [comment]
Hi Leigh,
Could you give me more contextual information. 
Do you get the error when running the govcr tests? Or is it with your own code (could you then post a snippet that reproduces the problem)?
What version of Go are you using?

**Comment by seborama** [comment]
Hi Leigh,
Could you give me more contextual information. 
Do you get the error when running the govcr tests? Or is it with your own code (could you then post a snippet that reproduces the problem)?
What version of Go are you using?

**Comment by leighmcculloch** [comment]
I'm running one of the tests on [github.com/lionelbarrow/braintree-go](https://github.com/lionelbarrow/braintree-go), checking out using govcr for it's integration test suite. The test makes a single outgoing request, and it seems to acknowledge that in the logs, and it's the govcr logs that print out the error.

```
$ go version
go version devel +e5b13401c6 Wed Jul 25 23:53:54 2018 +0000 linux/amd64
```

```
$ go test -tags='unit integration' -run=TestAllTransactionFields -v
=== RUN   TestAllTransactionFields
=== PAUSE TestAllTransactionFields
=== CONT  TestAllTransactionFields
2018/07/25 06:21:13 INFO - Cassette 'vcr' - Executing request to live server for POST https://api.sandbox.braintreegateway.com:443/merchants/4ngqq224rnk6gvxh/transactions
2018/07/25 06:21:15 INFO - Cassette 'vcr' - Recording new track for POST https://api.sandbox.braintreegateway.com:443/merchants/4ngqq224rnk6gvxh/transactions
2018/07/25 06:21:15 json: unsupported type: func(string, []uint8, int) ([]uint8, bool)
```

**Comment by seborama** [comment]
Hi,
If I read your lines correctly, you're using a dev version of Golang. Assuming this is correct, you need to delete your GOPATH/bin and GOPATH/pkg folders and recompile all your go utilities and projects. Could you try with an official release of Go? I have seen the error you mention with an unrelated project a few weeks ago when I was flipping back and forth between Go 1.9 and Go 1.10.

**Comment by seborama** [comment]
Hey @leighmcculloch,

Any luck?

Regards

**Comment by leighmcculloch** [comment]
@seborama Thanks for the suggestion. I did quickly try other versions of Go, but I still had the error. I haven't had a chance to return to this and investigate with a fresh install, etc. I'll drop a note here when I get to try it again.

**Comment by seborama** [comment]
This issue is stale and I'm closing it.
