### ISSUE TITLE
Remove "Path" from cassettes

### ISSUE THREAD

**Issue by klauspost** [seborama/govcr#37]
It seems that for no real reason, the full path is stored in a cassette:

```JSON
{
  "Name": "TestUnauth.gz",
  "Path": "/home/klaus/gopath/src/github.com/app/testdata",
  "Tracks": [ ....
 ```
This creates problems for me, when I run the cassette as part of a CI test, since the cassette is no longer at this path. Therefore I get an unexpected `mkdir /home/klaus: permission denied` when it wants to add to the cassette.

I don't see any reason to have this information inside the cassette since it must be provided anyway for loading it, and it only causes problems. So I'd propose to remove it.

**Comment by seborama** [comment]
I've created a new branch called Issue_37.
Is that working for you?

**Comment by klauspost** [comment]
Awesome! I will give it a spin tomorrow - if you open a PR I can comment on that :)

**Comment by seborama** [comment]
Cool, I've created PR #38. Let me know.

**Comment by seborama** [comment]
PR merged.
