### ISSUE TITLE
Handle concurrent roundtrips better

### ISSUE THREAD

**Issue by klauspost** [seborama/govcr#41]
Typically you would expect an `http.RoundTripper` to handle concurrent requests.

If we look at the [exiting Roundtripper](https://github.com/seborama/govcr/blob/abecfadb568e87402fcccfb7bd758d14facd2d79/vcr_transport.go#L17) it will cause race conditions on concurrent access.

A "simple" solution could be to put a `mu sync.Mutex` in the `vcrTransport` and add `t.mu.Lock() / defer t.mu.Unlock()` to the RoundTrip function. This could serialize roundtrips so only one can run at the time. It will not guarantee any order of recordings, but if you do concurrent requests you wouldn't expect to.

**Comment by seborama** [comment]
Good spot. I never considered concurrency for this until now. I'll give it some thinking. Maybe a mutex as you suggest in the (short?) term and something else when time permits...

**Comment by seborama** [comment]
Hi @klauspost ,

I've made some changes and added a test (TestConcurrencySafety).

Can you give it a spin and let me know how that works for you?

Cheers,
Seb
