### ISSUE TITLE
Ability to remove sensitive information from responses

### ISSUE THREAD

**Issue by michaelw** [seborama/govcr#42]
Sensitive headers (e.g., `Set-Cookie`) are stored in the cassette currently.  Is there a way to ensure they are not stored?

Currently, I am injecting a custom `RoundTripper`:
```go
func (tr *testScrubTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	resp, err := tr.Original.RoundTrip(req)
	if err == nil {
		// Scrub sensitive material here
		resp.Header.Del("Set-Cookie")
	}
	return resp, err
}
```

But it would be nice if we could use govcr's `ResponseFilter` machinery for this.

**Comment by seborama** [comment]
Hey, from version v5 of govcr, this is now possible using a recording track mutator.

See `AddRecordingMutators`, README and tests for details.

Sorry for the endless wait, I didn't have a personal use-case for govcr but recently that changed.

Following your issue and that of @klauspost at roughly the same time, about 3 years ago, I actually re-wrote much of govcr's code around formerly called Filters.

govcr now has track mutators, and they come inm2 flavours:
- recording track mutators - to modify the content saved to the cassette
- replaying track mutators (I will perhaps rename that to 'playback') - to modify the track at playback time (i.e. after it has been matched and retrieved from a cassette)

Best,
Seb
